name: Asana
on:
    pull_request:
        types: [opened, reopened]
    pull_request_review:
        types: [submitted]

jobs:
  change-dev-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
