name: Manual trigger
on:
    workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          asana-token: ${{ secrets.ASANA_SECRET }}
