name: Manual trigger
on:
    workflow_dispatch:

jobs:
    manual-trigger:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Run the action
          run: ./
